import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { Mail } from "lucide-react";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <div className="flex-grow">{children}</div>
          <Analytics />

          <footer className="text-center text-xs text-gray-500 border-t border-gray-200">
            <p className="px-8 py-2">
              <Link href="https://x.com/kotorisuke">
                <span className="flex items-center justify-end">
                  <Mail className="inline-block mr-2 h-3 w-3" />
                  ご意見・ご要望はXまで
                </span>
              </Link>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
